### ISSUE TITLE
Colon character (`:`) in topic causes publish to fail

### ISSUE THREAD

**Issue by kueblc** [taoyuan/mqttr#5]
Colon (`":"`) is a special character for `mqttr` when subscribing to topics, but when publishing there should be no such restriction. I believe this is caused by `publish` being passed `mqttTopic(topic)` instead of `topic`, which transforms the colon into "+".

https://github.com/taoyuan/mqttr/blob/96c259bc615c932680de96b4c1512e44583b24ed/src/client.ts#L210

As an aside, there should also be a way to escape a literal ":" when subscribing, if there isn't already.

**Comment by taoyuan** [comment]
This has been fixed in v3.0
